package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'TCDSL'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("TCDSL")) {
    val expected = GitVcsRoot({
        id("TCDSL")
        name = "This is TCDSL Root"
        url = "https://github.com/grmmvv/TCDSL.git"
        branch = "refs/heads/master"
        branchSpec = "refs/heads/*"
        checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.SHALLOW_CLONE
        authMethod = token {
            tokenId = "credentialsJSON:757b93d4-4abe-4211-a875-d15bb135d3da"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = ""
            password = "credentialsJSON:757b93d4-4abe-4211-a875-d15bb135d3da"
        }
    }

}
